spring:
  datasource:
    url: jdbc:postgresql://ep-tight-pine-a5xnjuks.us-east-2.aws.neon.tech:5432/neondb
    username: neondb_owner
    password: Hqrcgz1anW7O
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        namingStrategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect